### ISSUE TITLE
GitLab repository for Global App Menu seems to be gone

### ISSUE THREAD

**Issue by julianctni** [RabbitHols/Power-Gnome#2]
The gitlab repository for global app menu seems to be gone. :(

**Comment by RabbitHols** [comment]
Hi, you can use the extension packed in this repository at: 
https://github.com/RabbitHols/Unity-on-Gnome/tree/master/src/tweak_extension/gnomeGlobalAppMenu%40lestcape

**Comment by RabbitHols** [comment]
The problem it's fixed now the installer work like a charm
