### ISSUE TITLE
Remove Power Gnome

### ISSUE THREAD

**Issue by brandleesee** [RabbitHols/Power-Gnome#3]
Ciao!

Can you also add how to uninstall Power Gnome to README.md?

Thank you.

**Comment by RabbitHols** [comment]
Moved in TODO, will be done by this weekend.

**Comment by brandleesee** [comment]
any updates, @RabbitHols ?

**Comment by brandleesee** [comment]
not maintained anymore.... great! now I'll have to reverse the script on my own!
thank you!
